In [2]:
import numpy as np
import pandas as pd

In [ ]:
s1 = pd.Series([10, 20, 30, 40, 50])
print(type(s1))
s1

In [ ]:
s1.index

In [ ]:
s1.values

In [ ]:
print(type(s1.values), s1.values.dtype, s1.values.shape)

In [ ]:
s1.name = 'math_score'
s1

In [ ]:
s2 = pd.Series(['a', 'b', 'c', 1, 2, 3])
s2

In [ ]:
s2.values.dtype

In [ ]:
s3 = pd.Series([np.nan, 10, 30])
s3

In [ ]:
index_date = ['2021-10-06', '2021-10-07', '2021-10-08', '2021-10-09']
s4 = pd.Series([200, 195, np.nan, 205], index=index_date)
s4

In [ ]:
s4.index

In [ ]:
index_date = ['2021-10-06', '2021-10-07', '2021-10-08', '2021-10-09']
s4 = pd.Series([200, 195, np.nan, 205], index=index_date, name='sales')
s4

In [ ]:
s5 = pd.Series({'국어': 100, '영어': 95, '수학': 90})
s5

In [ ]:
pd.date_range(start='2021-10-06', end='2021-10-20')

In [ ]:
pd.date_range(start='2021/10/06', end='2021.10.20')

In [ ]:
pd.date_range(start='10-06-2021', end='10/20/2021')

In [ ]:
pd.date_range(start='2021-10-06', end='10.20.2021')

In [ ]:
pd.date_range(start='2021-10-06', periods=14)

In [ ]:
pd.date_range(start='2021-10-06', periods=4, freq='2D')

In [ ]:
pd.date_range(start='2021-10-06', periods=4, freq='W')

In [ ]:
pd.date_range(start='2021-10-06', periods=4, freq='W-MON')

In [ ]:
pd.date_range(start='2021-10-06', periods=4, freq='2BM')

In [ ]:
pd.date_range(start='2021-10-06', periods=4, freq='QS')

In [ ]:
pd.date_range(start='2021-10-06', periods=4, freq='AS')

In [ ]:
pd.date_range(start='2021-10-06 08:00', periods=10, freq='H')

In [ ]:
pd.date_range(start='2021-10-06 08:00', periods=10, freq='BH')

In [ ]:
pd.date_range(start='2021-10-06 08:00:00', periods=10, freq='30min')

In [ ]:
pd.date_range(start='2021-10-06 08:00:00', periods=10, freq='30T')

In [ ]:
pd.date_range(start='2021-10-06 08:00:00', periods=10, freq='10S')

In [ ]:
index_date = pd.date_range(start='2021-10-06', periods=5, freq='D')
s6 = pd.Series([51, 62, 55, 49, 58], index=index_date)
s6

In [ ]:
s6.index

In [ ]:
s7 = pd.Series(np.arange(10, 100, 10))
s7

In [ ]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df

In [ ]:
df = pd.DataFrame(np.arange(10, 100, 10).reshape(3, 3))
df

In [ ]:
stu_info = pd.DataFrame([[210253, '손흥민', '컴퓨터 공학과'],
                         [210254, '김광현', '경영학과'],
                         [210255, '류현진', '기계과']])
stu_info

In [ ]:
stu_arr = np.array([[210253, '손흥민', '컴퓨터 공학과'], [210254, '김광현', '경영학과'],
                    [210255, '류현진', '기계과']])
pd.DataFrame(stu_arr)

In [ ]:
df  = pd.DataFrame(np.arange(1, 13).reshape(4, 3), index=pd.date_range(start='2021-10-06', periods=4),
                   columns=['A', 'B', 'C'])
df

In [ ]:
data = {'연도': [2015, 2016, 2016, 2017, 2017], '지사': ['한국', '한국', '미국', '한국', '미국'],
        '고객 수': [200, 250, 450, 300, 500]}
data

In [ ]:
df = pd.DataFrame(data)
df

In [ ]:
s1 = pd.Series([2015, 2016, 2016, 2017, 2017])
s2 = pd.Series(['한국', '한국', '미국', '한국', '미국'])
s3 = pd.Series([200, 250, 450, 300, 500])

In [ ]:
df = pd.DataFrame()
df

In [ ]:
df['연도'] = s1
df

In [ ]:
df['지사'] = s2
df

In [ ]:
df['고객 수'] = s3
df

In [ ]:
df = pd.DataFrame({'연도': [2015, 2016, 2016, 2017, 2017],
                   '지사': ['한국', '한국', '미국', '한국', '미국'],
                   '고객 수': [200, 250, 450, 300, 500]})
df

In [ ]:
type(df['연도'])

In [ ]:
df['연도']

In [ ]:
df = pd.DataFrame({'연도': [2015, 2016, 2016, 2017, 2017],
                   '지사': ['한국', '한국', '미국', '한국', '미국'],
                   '고객 수': [200, 250, 450, 300, 500]}, columns=['지사', '연도', '고객 수'])
df

In [ ]:
df = pd.DataFrame({'연도': [2015, 2016, 2016, 2017, 2017],
                   '지사': ['한국', '한국', '미국', '한국', '미국'],
                   '고객 수': [200, 250, 450, 300, 500]}, columns=['지사', '연도', '고객 수'])
df

In [ ]:
'''
문제] data/coffee_shop_sales.txt 파일을 읽고 dict 를 생성한 후 DataFrame 을 생성하는 코드를 작성하세요.
        단, 날짜 값이 인덱스가 되어야 합니다.
'''

In [95]:
with open('../data/coffee_shop_sales.txt', 'rt', encoding='UTF-8') as f:
    lines = f.readlines()
    
header = lines[0].strip().split(' ')[1:]
lines = lines[1:]

In [96]:
coffee_sales = []
index_date = []

for i in range(len(header)):
    coffee_sales.append([]);
    
for line in lines:
    temp = line.strip().split(' ')
    index_date.append(temp[0])
    temp = temp[1:]
    
    for i in range(len(temp)):
        coffee_sales[i].append(int(temp[i]))
    
coffee_sales_dict = {}

for i in range(len(header)):
    coffee_sales_dict[header[i]] = coffee_sales[i]

In [97]:
df = pd.DataFrame(coffee_sales_dict, index=index_date)
df.index.name = '날짜'
df

에스프레소  아메리카노  카페라떼  카푸치노
날짜                             
10.05     10     50    45    20
10.06     12     45    41    18
10.07     11     53    52    25
10.08     15     49    38    22

In [ ]:
df

In [ ]:
df.index = range(1, 6)
df

In [ ]:
df.index

In [ ]:
df.columns

In [ ]:
df.values

In [ ]:
df['지사'].values

In [ ]:
s1 = pd.Series([10, 20, 30, 40, 50])
s2 = pd.Series([1, 2, 3, 4, 5])

In [ ]:
print(s1 + s2, end='\n\n')
print(s1 - s2, end='\n\n')
print(s1 * s2, end='\n\n')
print(s1 / s2, end='\n\n')
print(s1 // s2, end='\n\n')
print(s1 % s2, end='\n\n')
print(s1 ** s2, end='\n\n')

In [ ]:
print(s1 + 2, end='\n\n')
print(s1 - 2, end='\n\n')
print(s1 * 2, end='\n\n')
print(s1 / 2, end='\n\n')
print(s1 // 2, end='\n\n')
print(s1 % 2, end='\n\n')
print(s1 ** 2, end='\n\n')

In [ ]:
print(s1 == s2, end='\n\n')
print(s1 != s2, end='\n\n')
print(s1 >= s2, end='\n\n')
print(s1 > s2, end='\n\n')
print(s1 <= s2, end='\n\n')
print(s1 < s2, end='\n\n')

In [ ]:
s3 = pd.Series([True, False])
s4 = pd.Series([True, True])

In [ ]:
print(s3 & s4, end='\n\n')
print(s3 | s4, end='\n\n')
print(~s3, end='\n\n')

In [ ]:
a1 = np.array([10, 20, 30, 40, 50])
a2 = np.array([1, 2, 3, 4])

a1 + a2

In [ ]:
s1 = pd.Series(np.array([10, 20, 30, 40, 50]))
s2 = pd.Series(np.array([1, 2, 3, 4]))

s1 + s2

In [ ]:
s1 = pd.Series(np.array([10, 20, 30, 40, 50]), index=[1, 2, 3, 4, 5])
s2 = pd.Series(np.array([1, 2, 3, 4]), index=[4, 5, 6, 7])

s1 + s2

In [ ]:
df1 = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50], 'C': [100, 200, 300, 400, 500]})
df1

In [ ]:
df2 = pd.DataFrame({'A': [6, 7, 8], 'B': [60, 70, 80], 'C': [600, 700, 800]})
df2

In [ ]:
df1 + df2

In [ ]:
# 데이터프레임 간 비교, 논리 연산은 동일한 구조를 갖는 데이터프레임 사이에서만 가능하다!
df1 > df2

In [ ]:
df3 = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50], 'C': [100, 200, 300, 400, 500]},
                   index=[1, 2, 3, 4, 5])
df3

In [ ]:
df4 = pd.DataFrame({'B': [6, 7, 8], 'C': [60, 70, 80], 'D': [600, 700, 800]}, index=[4, 5, 6])
df4

In [ ]:
df3 + df4

In [3]:
df = pd.DataFrame({'봄': [256.5, 264.3, 215.9, 223.2, 312.8],
                   '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
                   '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
                   '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}, index=[2012, 2013, 2014, 2015, 2016])
df

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [ ]:
print(df.sum(), end='\n\n')
print(df.mean(), end='\n\n')
print(df.var(), end='\n\n')
print(df.std(), end='\n\n')
print(df.min(), end='\n\n')
print(df.max(), end='\n\n')

In [ ]:
df.cumsum()

In [ ]:
df.cumprod()

In [ ]:
df.sum()

In [ ]:
df.sum(axis=0)

In [ ]:
df.sum(axis=1)

In [ ]:
print(df.sum(axis=1), end='\n\n')
print(df.mean(axis=1), end='\n\n')
print(df.var(axis=1), end='\n\n')
print(df.std(axis=1), end='\n\n')
print(df.min(axis=1), end='\n\n')
print(df.max(axis=1), end='\n\n')

In [ ]:
df.cumsum(axis=1)

In [ ]:
df.cumprod(axis=1)

In [6]:
print(df['봄'].sum(), df['봄'].mean(), df['봄'].std(), df['봄'].var(), df['봄'].min(), df['봄'].max())

1272.6999999999998 254.53999999999996 38.62826685213822 1492.1430000000005 215.9 312.8


In [7]:
df['봄'].cumsum()

2012     256.5
2013     520.8
2014     736.7
2015     959.9
2016    1272.7
Name: 봄, dtype: float64

In [8]:
df['봄'].cumprod()

2012    2.565000e+02
2013    6.779295e+04
2014    1.463650e+07
2015    3.266866e+09
2016    1.021876e+12
Name: 봄, dtype: float64

In [ ]:
df.describe()

In [9]:
KTX_data = {'경부선KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
            '호남선KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
            '경전선KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
            '전라선KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
            '동해선KTX': [np.nan, np.nan, np.nan, np.nan, 2395, 3786, 6667],}
col_list = ['경부선KTX', '호남선KTX', '경전선KTX', '전라선KTX', '동해선KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']
df_KTX = pd.DataFrame(KTX_data, columns=col_list, index=index_list)
df_KTX

경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX
2011   39060    7313    3627     309     NaN
2012   39896    6967    4168    1771     NaN
2013   42005    6873    4088    1954     NaN
2014   43621    6626    4424    2244     NaN
2015   41702    8675    4606    3146  2395.0
2016   41266   10622    4984    3945  3786.0
2017   32427    9228    5570    5766  6667.0

In [10]:
df_KTX.index

Index(['2011', '2012', '2013', '2014', '2015', '2016', '2017'], dtype='object')

In [11]:
df_KTX.columns

Index(['경부선KTX', '호남선KTX', '경전선KTX', '전라선KTX', '동해선KTX'], dtype='object')

In [12]:
df_KTX.values

array([[39060.,  7313.,  3627.,   309.,    nan],
       [39896.,  6967.,  4168.,  1771.,    nan],
       [42005.,  6873.,  4088.,  1954.,    nan],
       [43621.,  6626.,  4424.,  2244.,    nan],
       [41702.,  8675.,  4606.,  3146.,  2395.],
       [41266., 10622.,  4984.,  3945.,  3786.],
       [32427.,  9228.,  5570.,  5766.,  6667.]])

In [13]:
df_KTX['경부선KTX'].values

array([39060, 39896, 42005, 43621, 41702, 41266, 32427], dtype=int64)

In [14]:
df_KTX['동해선KTX'].values

array([  nan,   nan,   nan,   nan, 2395., 3786., 6667.])

In [15]:
df_KTX.head()

경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX
2011   39060    7313    3627     309     NaN
2012   39896    6967    4168    1771     NaN
2013   42005    6873    4088    1954     NaN
2014   43621    6626    4424    2244     NaN
2015   41702    8675    4606    3146  2395.0

In [16]:
df_KTX.tail()

경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX
2013   42005    6873    4088    1954     NaN
2014   43621    6626    4424    2244     NaN
2015   41702    8675    4606    3146  2395.0
2016   41266   10622    4984    3945  3786.0
2017   32427    9228    5570    5766  6667.0

In [17]:
df_KTX.head(3)

경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX
2011   39060    7313    3627     309     NaN
2012   39896    6967    4168    1771     NaN
2013   42005    6873    4088    1954     NaN

In [18]:
df_KTX.tail(2)

경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX
2016   41266   10622    4984    3945  3786.0
2017   32427    9228    5570    5766  6667.0

In [19]:
df_KTX[1:2]

경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX
2012   39896    6967    4168    1771     NaN

In [21]:
df_KTX[1]
df_KTX[[1]]

KeyError: "None of [Int64Index([1], dtype='int64')] are in the [columns]"

In [22]:
df_KTX[2:5]

경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX
2013   42005    6873    4088    1954     NaN
2014   43621    6626    4424    2244     NaN
2015   41702    8675    4606    3146  2395.0

In [23]:
df_KTX.loc['2012']

경부선KTX    39896.0
호남선KTX     6967.0
경전선KTX     4168.0
전라선KTX     1771.0
동해선KTX        NaN
Name: 2012, dtype: float64

In [24]:
df_KTX.loc['2013':'2016']

경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX
2013   42005    6873    4088    1954     NaN
2014   43621    6626    4424    2244     NaN
2015   41702    8675    4606    3146  2395.0
2016   41266   10622    4984    3945  3786.0

In [25]:
df_KTX['동해선KTX']

2011       NaN
2012       NaN
2013       NaN
2014       NaN
2015    2395.0
2016    3786.0
2017    6667.0
Name: 동해선KTX, dtype: float64

In [26]:
df_KTX[['동해선KTX', '경전선KTX', '전라선KTX']]

동해선KTX  경전선KTX  전라선KTX
2011     NaN    3627     309
2012     NaN    4168    1771
2013     NaN    4088    1954
2014     NaN    4424    2244
2015  2395.0    4606    3146
2016  3786.0    4984    3945
2017  6667.0    5570    5766

In [29]:
df_KTX['경부선KTX']['2012':'2014']

2012    39896
2013    42005
2014    43621
Name: 경부선KTX, dtype: int64

In [30]:
df_KTX['경부선KTX'][1:4]

2012    39896
2013    42005
2014    43621
Name: 경부선KTX, dtype: int64

In [31]:
df_KTX.loc['2016']['호남선KTX']

10622.0

In [36]:
df_KTX.loc['2016']

경부선KTX    41266.0
호남선KTX    10622.0
경전선KTX     4984.0
전라선KTX     3945.0
동해선KTX     3786.0
Name: 2016, dtype: float64

In [32]:
df_KTX.loc['2016', '호남선KTX']

10622

In [33]:
df_KTX['호남선KTX']['2016']

10622

In [37]:
df_KTX['호남선KTX']

2011     7313
2012     6967
2013     6873
2014     6626
2015     8675
2016    10622
2017     9228
Name: 호남선KTX, dtype: int64

In [34]:
df_KTX['호남선KTX'][5]

10622

In [35]:
df_KTX['호남선KTX'].loc['2016']

10622

In [ ]:
'''
문제 1] df_KTX 에서 2012, 2014, 2015 년도의 경부선, 경전선, 전라선 KTX 고객의 수를 출력하는
        코드를 작성하세요.
        단, 위의 5가지 방법을 모두 사용하여 가능한 방법과 불가능한 방법을 식별하세요.
        
1) df_KTX.loc[['2012', '2014', '2015']][['경부선KTX', '경전선KTX', '전라선KTX']]    ==> OK
2) df_KTX.loc[['2012', '2014', '2015'], ['경부선KTX', '경전선KTX', '전라선KTX']]    ==> OK
3) df_KTX[['경부선KTX', '경전선KTX', '전라선KTX']][['2012', '2014', '2015']]        ==> Error
4) df_KTX[['경부선KTX', '경전선KTX', '전라선KTX']][[1, 3, 4]]                       ==> Error
5) df_KTX[['경부선KTX', '경전선KTX', '전라선KTX']].loc[['2012', '2014', '2015']]    ==> OK
'''

In [38]:
df_KTX.loc[['2012', '2014', '2015']][['경부선KTX', '경전선KTX', '전라선KTX']]

경부선KTX  경전선KTX  전라선KTX
2012   39896    4168    1771
2014   43621    4424    2244
2015   41702    4606    3146

In [39]:
df_KTX.loc[['2012', '2014', '2015'], ['경부선KTX', '경전선KTX', '전라선KTX']]

경부선KTX  경전선KTX  전라선KTX
2012   39896    4168    1771
2014   43621    4424    2244
2015   41702    4606    3146

In [40]:
df_KTX[['경부선KTX', '경전선KTX', '전라선KTX']][['2012', '2014', '2015']]

KeyError: "None of [Index(['2012', '2014', '2015'], dtype='object')] are in the [columns]"

In [41]:
df_KTX[['경부선KTX', '경전선KTX', '전라선KTX']][[1, 3, 4]]

KeyError: "None of [Int64Index([1, 3, 4], dtype='int64')] are in the [columns]"

In [42]:
df_KTX[['경부선KTX', '경전선KTX', '전라선KTX']].loc[['2012', '2014', '2015']]

경부선KTX  경전선KTX  전라선KTX
2012   39896    4168    1771
2014   43621    4424    2244
2015   41702    4606    3146

In [ ]:
'''
문제 2] df_KTX 에서 2013 년도 부터 2016 년도 까지의 호남선 부터 전라선 KTX 까지의 고객의 수를 출력하는
        코드를 작성하세요.
        단, 위의 5가지 방법을 모두 사용하여 가능한 방법과 불가능한 방법을 식별하세요.

1) df_KTX.loc['2013':'2016']['호남선KTX':'전라선KTX']        ==> Fail
2) df_KTX.loc['2013':'2016', '호남선KTX':'전라선KTX']        ==> OK
3) df_KTX['호남선KTX':'전라선KTX']['2013':'2016']            ==> Fail
4) df_KTX['호남선KTX':'전라선KTX'][2:6]                      ==> Fail
5) df_KTX['호남선KTX':'전라선KTX'].loc['2013':'2016']        ==> Fail
'''

In [43]:
df_KTX.loc['2013':'2016']['호남선KTX':'전라선KTX']

Empty DataFrame
Columns: [경부선KTX, 호남선KTX, 경전선KTX, 전라선KTX, 동해선KTX]
Index: []

In [44]:
df_KTX.loc['2013':'2016', '호남선KTX':'전라선KTX']

호남선KTX  경전선KTX  전라선KTX
2013    6873    4088    1954
2014    6626    4424    2244
2015    8675    4606    3146
2016   10622    4984    3945

In [45]:
df_KTX['호남선KTX':'전라선KTX']['2013':'2016']

Empty DataFrame
Columns: [경부선KTX, 호남선KTX, 경전선KTX, 전라선KTX, 동해선KTX]
Index: []

In [46]:
df_KTX['호남선KTX':'전라선KTX'][2:6]

Empty DataFrame
Columns: [경부선KTX, 호남선KTX, 경전선KTX, 전라선KTX, 동해선KTX]
Index: []

In [47]:
df_KTX['호남선KTX':'전라선KTX'].loc['2013':'2016']

Empty DataFrame
Columns: [경부선KTX, 호남선KTX, 경전선KTX, 전라선KTX, 동해선KTX]
Index: []

In [49]:
df_KTX.loc[['2013', '2015', '2016'], '호남선KTX':'전라선KTX']

호남선KTX  경전선KTX  전라선KTX
2013    6873    4088    1954
2015    8675    4606    3146
2016   10622    4984    3945

In [50]:
df_KTX.loc['2013':'2016', ['호남선KTX', '경부선KTX', '전라선KTX']]

호남선KTX  경부선KTX  전라선KTX
2013    6873   42005    1954
2014    6626   43621    2244
2015    8675   41702    3146
2016   10622   41266    3945

In [51]:
df_KTX.T

2011     2012     2013     2014     2015     2016     2017
경부선KTX  39060.0  39896.0  42005.0  43621.0  41702.0  41266.0  32427.0
호남선KTX   7313.0   6967.0   6873.0   6626.0   8675.0  10622.0   9228.0
경전선KTX   3627.0   4168.0   4088.0   4424.0   4606.0   4984.0   5570.0
전라선KTX    309.0   1771.0   1954.0   2244.0   3146.0   3945.0   5766.0
동해선KTX      NaN      NaN      NaN      NaN   2395.0   3786.0   6667.0

In [52]:
df_KTX[['호남선KTX', '경부선KTX', '전라선KTX']]

호남선KTX  경부선KTX  전라선KTX
2011    7313   39060     309
2012    6967   39896    1771
2013    6873   42005    1954
2014    6626   43621    2244
2015    8675   41702    3146
2016   10622   41266    3945
2017    9228   32427    5766

In [53]:
df1 = pd.DataFrame({'class1': [92, 85, 90, 88], 'class2': [80, 84, 92, 87]})
df1

class1  class2
0      92      80
1      85      84
2      90      92
3      88      87

In [54]:
df2 = pd.DataFrame({'class1': [95, 88], 'class2': [84, 92]})
df2

class1  class2
0      95      84
1      88      92

In [55]:
df1.append(df2)

class1  class2
0      92      80
1      85      84
2      90      92
3      88      87
0      95      84
1      88      92

In [57]:
df1.append(df2, ignore_index=True)

class1  class2
0      92      80
1      85      84
2      90      92
3      88      87
4      95      84
5      88      92

In [58]:
df1

class1  class2
0      92      80
1      85      84
2      90      92
3      88      87

In [59]:
df3 = pd.DataFrame({'class1': [85, 90]})
df3

class1
0      85
1      90

In [61]:
df2.append(df3, ignore_index=True)

class1  class2
0      95    84.0
1      88    92.0
2      85     NaN
3      90     NaN

In [66]:
df2a = pd.DataFrame({'class2': [95, 88], 'class3': [84, 92]})
df2a

class2  class3
0      95      84
1      88      92

In [67]:
df1.append(df2a, ignore_index=True)

class1  class2  class3
0    92.0      80     NaN
1    85.0      84     NaN
2    90.0      92     NaN
3    88.0      87     NaN
4     NaN      95    84.0
5     NaN      88    92.0

In [68]:
df4 = pd.DataFrame({'class3': [84, 92, 85, 95]})
df4

class3
0      84
1      92
2      85
3      95

In [69]:
df1.join(df4)

class1  class2  class3
0      92      80      84
1      85      84      92
2      90      92      85
3      88      87      95

In [70]:
df1a = pd.DataFrame({'class1': [92, 85, 90, 88], 'class2': [80, 84, 92, 87]},
                    index=['a', 'b', 'c', 'd'])
df1a

class1  class2
a      92      80
b      85      84
c      90      92
d      88      87

In [71]:
df4a = pd.DataFrame({'class3': [84, 92, 85, 95]}, index=['a', 'b', 'c', 'd'])
df4a

class3
a      84
b      92
c      85
d      95

In [72]:
df1a.join(df4a)

class1  class2  class3
a      92      80      84
b      85      84      92
c      90      92      85
d      88      87      95

In [73]:
df4b = pd.DataFrame({'class3': [84, 92, 85, 95]}, index=['c', 'd', 'e', 'f'])
df4b

class3
c      84
d      92
e      85
f      95

In [76]:
df1a.join(df4b)

class1  class2  class3
a      92      80     NaN
b      85      84     NaN
c      90      92    84.0
d      88      87    92.0

In [77]:
df4b.join(df1a)

class3  class1  class2
c      84    90.0    92.0
d      92    88.0    87.0
e      85     NaN     NaN
f      95     NaN     NaN

In [78]:
df4c = pd.DataFrame({'class2': [80, 90, 87, 93], 'class3': [84, 92, 85, 95]},
                    index=['c', 'd', 'e', 'f'])
df4c

class2  class3
c      80      84
d      90      92
e      87      85
f      93      95

In [81]:
df1a.join(df4c)

ValueError: columns overlap but no suffix specified: Index(['class2'], dtype='object')

In [82]:
df_A_B = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'], '제품A': [50, 51, 52, 53],
                       '제품B': [60, 61, 62, 63]})
df_A_B

판매월  제품A  제품B
0  1월   50   60
1  2월   51   61
2  3월   52   62
3  4월   53   63

In [83]:
df_C_D = pd.DataFrame({'판매월': ['4월', '3월', '2월', '1월'], '제품C': [70, 71, 72, 73],
                       '제품D': [80, 81, 82, 83]})
df_C_D

판매월  제품C  제품D
0  4월   70   80
1  3월   71   81
2  2월   72   82
3  1월   73   83

In [84]:
df_A_B.merge(df_C_D)

판매월  제품A  제품B  제품C  제품D
0  1월   50   60   73   83
1  2월   51   61   72   82
2  3월   52   62   71   81
3  4월   53   63   70   80

In [85]:
df_C_D_a = pd.DataFrame({'판매월': ['4월', '4월', '3월', '2월', '2월', '1월'],
                        '제품C': [70, 71, 75, 72, 76, 73],
                        '제품D': [80, 81, 85, 82, 86, 83]})
df_C_D_a

판매월  제품C  제품D
0  4월   70   80
1  4월   71   81
2  3월   75   85
3  2월   72   82
4  2월   76   86
5  1월   73   83

In [86]:
df_A_B.merge(df_C_D_a)

판매월  제품A  제품B  제품C  제품D
0  1월   50   60   73   83
1  2월   51   61   72   82
2  2월   51   61   76   86
3  3월   52   62   75   85
4  4월   53   63   70   80
5  4월   53   63   71   81

In [87]:
df_C_D_a.merge(df_A_B)

판매월  제품C  제품D  제품A  제품B
0  4월   70   80   53   63
1  4월   71   81   53   63
2  3월   75   85   52   62
3  2월   72   82   51   61
4  2월   76   86   51   61
5  1월   73   83   50   60

In [88]:
df_C_D_b = pd.DataFrame({'판매월': ['3월', '4월', '5월', '6월'],
                        '제품C': [70, 71, 72, 73],
                        '제품D': [80, 81, 82, 83]})
df_C_D_b

판매월  제품C  제품D
0  3월   70   80
1  4월   71   81
2  5월   72   82
3  6월   73   83

In [90]:
df_A_B.merge(df_C_D_b)

판매월  제품A  제품B  제품C  제품D
0  3월   52   62   70   80
1  4월   53   63   71   81

In [91]:
df_A_B.merge(df_C_D_b, how='inner')

판매월  제품A  제품B  제품C  제품D
0  3월   52   62   70   80
1  4월   53   63   71   81

In [92]:
df_A_B.merge(df_C_D_b, how='left')

판매월  제품A  제품B   제품C   제품D
0  1월   50   60   NaN   NaN
1  2월   51   61   NaN   NaN
2  3월   52   62  70.0  80.0
3  4월   53   63  71.0  81.0

In [93]:
df_A_B.merge(df_C_D_b, how='right')

판매월   제품A   제품B  제품C  제품D
0  3월  52.0  62.0   70   80
1  4월  53.0  63.0   71   81
2  5월   NaN   NaN   72   82
3  6월   NaN   NaN   73   83

In [94]:
df_A_B.merge(df_C_D_b, how='outer')

판매월   제품A   제품B   제품C   제품D
0  1월  50.0  60.0   NaN   NaN
1  2월  51.0  61.0   NaN   NaN
2  3월  52.0  62.0  70.0  80.0
3  4월  53.0  63.0  71.0  81.0
4  5월   NaN   NaN  72.0  82.0
5  6월   NaN   NaN  73.0  83.0

In [ ]:
'''
문제] data/coffee_shop_sales.txt 파일을 읽고 다음의 결과를 출력하는 코드를 작성하세요.
        단, pandas 기반으로 코드를 작성하여야 합니다.
        
-------------------------------------------------
에스프레소: [10, 12, 11, 15]
    전체 판매량: 48, 평균 판매량 12.0
아메리카노: [xx, xx, xx, xx]
    전체 판매량: xx, 평균 판매량 xx.x
카페라떼: [xx, xx, xx, xx]
    전체 판매량: xx, 평균 판매량 xx.x
카푸치노: [xx, xx, xx, xx]
    전체 판매량: xx, 평균 판매량 xx.x
'''

In [100]:
df = pd.read_csv('../data/coffee_shop_sales.txt', sep=' ', index_col='날짜')
df

에스프레소  아메리카노  카페라떼  카푸치노
날짜                             
10.05     10     50    45    20
10.06     12     45    41    18
10.07     11     53    52    25
10.08     15     49    38    22

In [103]:
print(df['에스프레소'].values, df['에스프레소'].sum(), df['에스프레소'].mean())
print(df['아메리카노'].values, df['아메리카노'].sum(), df['아메리카노'].mean())
print(df['카페라떼'].values, df['카페라떼'].sum(), df['카페라떼'].mean())
print(df['카푸치노'].values, df['카푸치노'].sum(), df['카푸치노'].mean())

[10 12 11 15] 48 12.0
[50 45 53 49] 197 49.25
[45 41 52 38] 176 44.0
[20 18 25 22] 85 21.25


In [104]:
%%writefile ../data/sea_rain1.csv
연도,동행,남해,서해,전체
1996,17.4629,17.2288,14.436,15.9067
1997,17.4116,17.4092,14.8248,16.1526
1998,17.5944,18.011,15.2512,16.6044
1999,18.1495,18.3175,14.8979,16.6284
2000,17.9288,18.1766,15.0504,16.6178

Writing ../data/sea_rain1.csv


In [105]:
df = pd.read_csv('../data/sea_rain1.csv')
df

연도       동행       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [106]:
df = pd.read_csv('../data/sea_rain1_from_notepad.csv')
df

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte

In [107]:
df = pd.read_csv('../data/sea_rain1_from_notepad.csv', encoding='CP949')
df

연도       동행       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [108]:
df = pd.read_csv('../data/sea_rain1_from_notepad.csv', encoding='MS949')
df

연도       동행       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [109]:
%%writefile ../data/sea_rain1_space.txt
연도 동행 남해 서해 전체
1996 17.4629 17.2288 14.436 15.9067
1997 17.4116 17.4092 14.8248 16.1526
1998 17.5944 18.011 15.2512 16.6044
1999 18.1495 18.3175 14.8979 16.6284
2000 17.9288 18.1766 15.0504 16.6178

Writing ../data/sea_rain1_space.txt


In [110]:
df = pd.read_csv('../data/sea_rain1_space.txt', sep=' ')
df

연도       동행       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [111]:
df = pd.read_csv('../data/sea_rain1_space.txt', sep=' ', index_col='연도')
df

동행       남해       서해       전체
연도                                      
1996  17.4629  17.2288  14.4360  15.9067
1997  17.4116  17.4092  14.8248  16.1526
1998  17.5944  18.0110  15.2512  16.6044
1999  18.1495  18.3175  14.8979  16.6284
2000  17.9288  18.1766  15.0504  16.6178

In [121]:
df_WH = pd.DataFrame({'Weight': [62, 67, 55, 74], 'Height': [165, 177, 160, 180]},
                     index=['ID_1', 'ID_2', 'ID_3', 'ID_4'])
df_WH.index.name = 'User'
df_WH

Weight  Height
User                
ID_1      62     165
ID_2      67     177
ID_3      55     160
ID_4      74     180

In [122]:
bmi = df_WH['Weight'] / (df_WH['Height'] / 100) ** 2
bmi

User
ID_1    22.773186
ID_2    21.385936
ID_3    21.484375
ID_4    22.839506
dtype: float64

In [123]:
df_WH['BMI'] = bmi
df_WH

Weight  Height        BMI
User                           
ID_1      62     165  22.773186
ID_2      67     177  21.385936
ID_3      55     160  21.484375
ID_4      74     180  22.839506

In [124]:
df_WH.to_csv('../data/save_DataFrame.csv')

In [125]:
df_pr = pd.DataFrame({'판매가격': [2000, 3000, 5000, 10000], '판매량': [32, 53, 40, 25]},
                     index=['P1001', 'P1002', 'P1003', 'P1004'])
df_pr.index.name = '제품번호'
df_pr

판매가격  판매량
제품번호             
P1001   2000   32
P1002   3000   53
P1003   5000   40
P1004  10000   25

In [128]:
df_pr.to_csv('../data/save_DataFrame_cp949.txt', sep=' ', encoding='CP949')