In [2]:
import numpy as np

In [ ]:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lst

In [ ]:
'''
lst 리스트에 저장된 값을 다음과 같이 출력하는 코드를 작성하세요.

1 2 3
4 5 6
7 8 9
'''

In [4]:
for sub_lst in lst:
    for val in sub_lst:
        print(val, end=' ')
        
    print()

1 2 3 
4 5 6 
7 8 9 


In [6]:
for i in range(len(lst)):
    for j in range(len(lst[i])):
        print(lst[i][j], end=' ')
        
    print()

1 2 3 
4 5 6 
7 8 9 


In [ ]:
'''
lst 리스트에 저장된 모든 값을 제곱한 후 다음과 같이 출력하는 코드를 작성하세요.
단, 원래 리스트의 내용이 제곱된 값으로 변경되어야 합니다.

 1  4  9
16 25 36
49 64 81
'''

In [9]:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for i in range(len(lst)):
    for j in range(len(lst[i])):
        lst[i][j] **= 2
        print('%2d' % (lst[i][j]), end=' ')
        
    print()

 1  4  9 
16 25 36 
49 64 81 


In [10]:
lst

[[1, 4, 9], [16, 25, 36], [49, 64, 81]]

In [11]:
lst[1] = 'Apple'
lst

[[1, 4, 9], 'Apple', [49, 64, 81]]

In [ ]:
'''
1. 다음 리스트의 내용을 C:\projects\myPyCode\data\lst.csv 파일로 저장하는 코드를 작성하세요.

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[lst.csv]
1,2,3
4,5,6
7,8,9

2. lst.csv 파일을 읽어 각 값을 제곱하여 lst2 리스트로 저장한 후 출력하는 코드를 작성하세요.
lst2 => [[1, 4, 9], [16, 25, 36], [49, 64, 81]]

 1  4  9 
16 25 36 
49 64 81
'''

In [14]:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

f = open('../data/lst.csv', 'wt')

for i in range(len(lst)):
    for j in range(len(lst[i])):
        if j < (len(lst[i]) - 1):
            f.write(str(lst[i][j]) + ',')
        else:
            f.write(str(lst[i][j]))
        
    f.write('\n')
    
f.close()

In [23]:
f = open('../data/lst.csv', 'rt')
lst2 = f.readlines()
f.close()

for i in range(len(lst2)):
    lst2[i] = lst2[i].split()[0].split(',')
    
    for j in range(len(lst2[i])):
        lst2[i][j] = int(lst2[i][j])
        lst2[i][j] **= 2
        
        print('%2d' % (lst2[i][j]), end=' ')
        
    print()
    
print(lst2)

 1  4  9 
16 25 36 
49 64 81 
[[1, 4, 9], [16, 25, 36], [49, 64, 81]]


In [32]:
lst1 = [1, 2, 3, 4, 5]

arr1 = np.array(lst1)

print(type(arr1), arr1)
arr1

<class 'numpy.ndarray'> [1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [33]:
print(type(3.4), type(3.), type(.4))

<class 'float'> <class 'float'> <class 'float'>


In [34]:
lst2 = [0.1, 2, 3, 4, 0.5]

arr2 = np.array(lst2)

arr2

array([0.1, 2. , 3. , 4. , 0.5])

In [35]:
arr1.dtype

dtype('int32')

In [36]:
arr2.dtype

dtype('float64')

In [37]:
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr = np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [39]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
arr2 = arr1.reshape(4, 3)

In [51]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
arr1.reshape(4, 4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [54]:
arr1.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [55]:
arr = np.arange(12).reshape(4, 3)
arr.shape

(4, 3)

In [56]:
arr = np.arange(5)
arr.shape

(5,)

In [57]:
lst = [10]
lst

[10]

In [60]:
tpl1 = (10, 20)
type(tpl1)

tuple

In [61]:
tpl2 = (10)
type(tpl2)

int

In [62]:
tpl3 = (10,)
type(tpl3)

tuple

In [66]:
arr = np.linspace(1, 10, 10)
arr.dtype

dtype('float64')

In [64]:
arr = np.linspace(0, np.pi, 20)
arr

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [65]:
arr = np.linspace(0, np.pi)
arr

array([0.        , 0.06411414, 0.12822827, 0.19234241, 0.25645654,
       0.32057068, 0.38468481, 0.44879895, 0.51291309, 0.57702722,
       0.64114136, 0.70525549, 0.76936963, 0.83348377, 0.8975979 ,
       0.96171204, 1.02582617, 1.08994031, 1.15405444, 1.21816858,
       1.28228272, 1.34639685, 1.41051099, 1.47462512, 1.53873926,
       1.60285339, 1.66696753, 1.73108167, 1.7951958 , 1.85930994,
       1.92342407, 1.98753821, 2.05165235, 2.11576648, 2.17988062,
       2.24399475, 2.30810889, 2.37222302, 2.43633716, 2.5004513 ,
       2.56456543, 2.62867957, 2.6927937 , 2.75690784, 2.82102197,
       2.88513611, 2.94925025, 3.01336438, 3.07747852, 3.14159265])

In [67]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
arr = np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
arr1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
arr1.astype(float)

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [75]:
arr1.dtype

dtype('<U5')

In [76]:
arr2 = arr1.astype(float)
arr2

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [77]:
arr2.dtype

dtype('float64')

In [78]:
arr2 = arr1.astype(np.float32)
print(arr2.dtype, arr2)

float32 [1.567 0.123 5.123 9.    8.   ]


In [79]:
arr2 = arr1.astype(np.float64)
print(arr2.dtype, arr2)

float64 [1.567 0.123 5.123 9.    8.   ]


In [80]:
arr1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
arr2 = arr1.astype(np.int32)
print(arr2.dtype, arr2)

ValueError: invalid literal for int() with base 10: '1.567'

In [81]:
str1 = '1.234'

num1 = int(str1)

ValueError: invalid literal for int() with base 10: '1.234'

In [82]:
str1 = '1.234'

num1 = int(float(str1))
num1

1

In [84]:
arr1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
arr2 = arr1.astype(np.float64)
arr3 = arr2.astype(np.int64)
print(arr2, arr3)

[1.567 0.123 5.123 9.    8.   ] [1 0 5 9 8]


In [85]:
np.random.rand()

0.6248310284554323

In [86]:
np.random.rand(3, 4)

array([[0.47673084, 0.75369735, 0.22260021, 0.38568178],
       [0.39577949, 0.80130853, 0.59611963, 0.31656958],
       [0.86464941, 0.81545304, 0.46702138, 0.75324027]])

In [87]:
np.random.rand(2, 3, 4)

array([[[0.06154907, 0.82326313, 0.36740845, 0.8730981 ],
        [0.93138298, 0.86831378, 0.65600083, 0.66153048],
        [0.44358543, 0.43697339, 0.08577845, 0.50856932]],

       [[0.32178175, 0.64848211, 0.04504159, 0.55221599],
        [0.62238094, 0.7349387 , 0.85439048, 0.6869426 ],
        [0.58768645, 0.27636511, 0.55272719, 0.16230843]]])

In [94]:
import random

random.randint(0, 3)

3

In [159]:
np.random.randint(0, 3)

1

In [192]:
np.random.randint(0, 10, size=(3, 4))

array([[4, 1, 6, 0],
       [3, 3, 6, 6],
       [2, 4, 3, 4]])

In [201]:
np.random.randint(0, 10, size=(5,))

array([8, 5, 0, 7, 1])

In [ ]:
'''
x = [1, 2, 3, 4, 5]
y = 4x^2 + 3x + 4
'''

In [202]:
x = [1, 2, 3, 4, 5]
y = []

for val in x:
    temp = 4 * val ** 2 + 3 * val + 4
    y.append(temp)
    
y

[11, 26, 49, 80, 119]

In [203]:
x = np.array(x)
y = 4 * x ** 2 + 3 * x + 4
y

array([ 11,  26,  49,  80, 119])

In [204]:
x ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [205]:
4 * x ** 2

array([  4,  16,  36,  64, 100], dtype=int32)

In [206]:
3 * x

array([ 3,  6,  9, 12, 15])

In [207]:
4 * x ** 2 + 3 * x

array([  7,  22,  45,  76, 115])

In [208]:
4 * x ** 2 + 3 * x + 4

array([ 11,  26,  49,  80, 119])

In [209]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [210]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 // arr2)
print(arr1 % arr2)
print(arr1 ** arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[10 10 10 10]
[0 0 0 0]
[     10     400   27000 2560000]


In [211]:
print(arr1, arr2)

[10 20 30 40] [1 2 3 4]


In [212]:
print(arr1 + 2)
print(arr1 - 2)
print(arr1 * 2)
print(arr1 / 2)
print(arr1 // 2)
print(arr1 % 2)
print(arr1 ** 2)

[12 22 32 42]
[ 8 18 28 38]
[20 40 60 80]
[ 5. 10. 15. 20.]
[ 5 10 15 20]
[0 0 0 0]
[ 100  400  900 1600]


In [213]:
arr1

array([10, 20, 30, 40])

In [216]:
arr1 = np.array([10, 20, 30, 40])
arr1 += 2
print(arr1)

[12 22 32 42]


In [217]:
arr1 = np.array([10, 20, 30, 40])
arr1 /= 2
print(arr1)

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

In [218]:
arr1 = np.array([10, 20, 30, 40])
arr1 = arr1.astype(np.float64) / 2
print(arr1)

[ 5. 10. 15. 20.]


In [220]:
arr1 = np.array([10, 20, 30, 40])
arr1 **= 2
print(arr1)

[ 100  400  900 1600]


In [221]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4, 5])

In [222]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [223]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [225]:
print(arr1 == arr2)
print(arr1 != arr2)
print(arr1 >= arr2)
print(arr1 > arr2)
print(arr1 <= arr2)
print(arr1 < arr2)

[False False False False]
[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]
[False False False False]
[False False False False]


In [226]:
print(arr1, arr2)

[10 20 30 40] [1 2 3 4]


In [227]:
print(arr1 == 10)
print(arr1 != 10)
print(arr1 >= 10)
print(arr1 > 10)
print(arr1 <= 10)
print(arr1 < 10)

[ True False False False]
[False  True  True  True]
[ True  True  True  True]
[False  True  True  True]
[ True False False False]
[False False False False]


In [230]:
arr1 and arr2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [231]:
arr1 = np.array([True, False])
arr2 = np.array([True, True])

In [233]:
arr1 or arr2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [234]:
np.logical_and(arr1, arr2)

array([ True, False])

In [237]:
arr1 & arr2

array([ True, False])

In [235]:
np.logical_or(arr1, arr2)

array([ True,  True])

In [238]:
arr1 | arr2

array([ True,  True])

In [236]:
np.logical_not(arr1)

array([False,  True])

In [239]:
~arr1

array([False,  True])

In [247]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [241]:
arr.sum()

10

In [242]:
arr.mean()

2.0

In [243]:
arr.std()

1.4142135623730951

In [244]:
arr.var()

2.0

In [245]:
arr.min()

0

In [246]:
arr.max()

4

In [248]:
arr.cumsum()

array([ 0,  1,  3,  6, 10], dtype=int32)

In [249]:
arr.cumprod()

array([0, 0, 0, 0, 0], dtype=int32)

In [250]:
arr

array([0, 1, 2, 3, 4])

In [251]:
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

In [252]:
arr.cumprod()

array([  1,   2,   6,  24, 120], dtype=int32)

In [257]:
print(arr, arr.mean(), arr.var(), arr.std())

[1 2 3 4 5] 3.0 2.0 1.4142135623730951


In [258]:
import math

math.sqrt(2.0)

1.4142135623730951

In [ ]:
'''

넘파이 배열 다루기

넘파이는 넘파이 따로 배열을 구현(내부적으로 C언어)

베이스
np.array(seq_data)

배열 객체의 타입 확인 
a1.dtype
    => dtype('int32')

배열의 형 변환
numarr = strarr.astype(dtype)
새로운 배열을 생성하므로 저장해야함

넘파이에선 배열끼리 비교연산 가능

int에선 나누기가 오류나니 float으로 변환해버 나눠야 함


행렬 연산

행렬곱  A.dot(B), np.dot(A,B)
전치행렬 A.transpose
역행렬 np.linalg.inv(A)
행렬식 determinant np.linalg.det(A)

다차원 배열 생성
.reshape(2,2) - 2x2로


'''

In [4]:
arr = np.arange(10, 100, 10).reshape(3,3)

In [46]:

arr[0:3,1:2]



array([[20],
       [50],
       [80]])

In [47]:

arr[0:3,1]

array([20, 50, 80])

In [53]:
arr[[0,2]][:,[0,2]]

array([[10, 30],
       [70, 90]])